name: angelgene
favicon: null
layout_spectrum: 0.23238
typography_spectrum: 0.71843
title: angelgene
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1af8c'
    - '#fefeeb'
    - '#531000'
    - '#955829'
    - '#ba7a3a'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
