name: Angel Gené
favicon: null
layout_spectrum: 0.63671
typography_spectrum: 0.55754
title: angelgene
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5d6bb'
    - '#eb8b12'
    - '#000015'
    - '#3d3531'
    - '#cc2622'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
