name: angelgene
favicon: null
layout_spectrum: 0.23238
typography_spectrum: 0.71843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160d10'
    - '#444d4a'
    - '#f5e7cd'
    - '#bd9ea4'
    - '#985d57'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
